### ISSUE TITLE
Volumes creation not working well for certain OS directory structures (problematic docker-compose.yaml files)

### ISSUE THREAD

**Issue by realvarx** [atsign-foundation/dess#31]
**Describe the bug**
Current volumes from docker-swarm.yaml file not working well for certain OS directory structures, resulting in incorrect docker-compose.yaml volumes which won't let the dess service start (invalid mount config).

**To Reproduce**
1. First I Choose an outdated OS version for your machine, such as `Ubuntu 18.04.6 LTS (arm64)`
2. Then I Install dess and run `dess-create` command following [Instructions.md](https://github.com/atsign-foundation/dess/blob/trunk/Instructions.md)
3. And then check running services with `sudo docker service ls`. Secondary will have 0/1 replicas.
```
ID             NAME                     MODE         REPLICAS   IMAGE                          PORTS
6g3caz8bx4n0   fluttering80_secondary   replicated   0/1        atsigncompany/secondary:dess   *:6464->6464/tcp
rxtsooogkusp   secondaries_shepherd     replicated   1/1        mazzolino/shepherd:latest
```
4. `sudo docker service ps [@atsign]_secondary` will show `invalid mount config` error for dess container.
```
ID             NAME                           IMAGE                          NODE               DESIRED STATE   CURRENT STATE                      ERROR                              PORTS
lovlgnu1au0b   fluttering80_secondary.1       atsigncompany/secondary:dess   ip-203-0-113-175   Ready           Preparing less than a second ago
ckhm3cqpdlck    \_ fluttering80_secondary.1   atsigncompany/secondary:dess   ip-203-0-113-175   Shutdown        Rejected 4 seconds ago             "invalid mount config for type…"
5dasd2gij31r    \_ fluttering80_secondary.1   atsigncompany/secondary:dess   ip-203-0-113-175   Shutdown        Rejected 9 seconds ago             "invalid mount config for type…"
vfqok7f4juwv    \_ fluttering80_secondary.1   atsigncompany/secondary:dess   ip-203-0-113-175   Shutdown        Rejected 14 seconds ago            "invalid mount config for type…"
ltr0z48uxrgr    \_ fluttering80_secondary.1   atsigncompany/secondary:dess   ip-203-0-113-175   Shutdown        Rejected 19 seconds ago            "invalid mount config for type…"
```
5. `ubuntu@ip-203-0-113-175:/home/atsign/dess/[@sign]$ cat docker-compose.yaml` will show that volume generation did not go as expected.

**Expected behavior**
Volumes generation working propperly.

**Screenshots**
Current docker-compose.yaml file:
```
ubuntu@ip-203-0-113-175:/home/atsign/dess/@fluttering80$ cat docker-compose.yaml
networks:
  second:
    external: true
    name: secondaries
services:
  secondary:
    command: -a @fluttering80 -p 6464 -s 94003d4f67b452b36974889cf2493b07fff010689a44fab7ac7dd83aa95399eb996925c7c6a7b4802ed401b7a9c77e1e542f0f47c785cdb64e58a9
    image: atsigncompany/secondary:dess
    networks:
      second: {}
    ports:
    - published: 6464
      target: 6464
    volumes:
    - /home/ubuntu/atsign/etc/live/dess.example.com:/atsign/certs:rw
    - /home/ubuntu/atsign/etc/archive/dess.example.com:/archive/dess.example.com:rw
    - /home/ubuntu/atsign/@fluttering80:/atsign/storage:rw
version: '3.7'
```

Expected docker-compose.yaml file:
```
ubuntu@ip-203-0-113-175:/home/atsign/dess/@fluttering80$ cat docker-compose.yaml
networks:
  second:
    external: true
    name: secondaries
services:
  secondary:
    command: -a @fluttering80 -p 6464 -s 94003d4f67b452b36974889cf2493b07fff010689a44fab7ac7dd83aa95399eb996925c7c6a7b4802ed401b7a9c77e1e542f0f47c785cdb64e58ca9d98593ca9
    image: atsigncompany/secondary:dess
    networks:
      second: {}
    ports:
    - published: 6464
      target: 6464
    volumes:
    - /home/atsign/atsign/etc/live/dess.example.com:/atsign/certs:rw
    - /home/atsign/atsign/etc/archive/dess.example.com:/archive/dess.example.com:rw
    - /home/atsign/atsign/@fluttering80/storage:/atsign/storage:rw
version: '3.7'
```
**Additional context**
Error may be located on [create.sh](https://github.com/atsign-foundation/dess/blob/trunk/create.sh) file.
